//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Ragnarok/Input/RagnarokVRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RagnarokVRInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RagnarokVRInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RagnarokVRInputActions"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""2535e272-61c8-4627-acba-56a454780cdb"",
            ""actions"": [
                {
                    ""name"": ""Grip Left"",
                    ""type"": ""Button"",
                    ""id"": ""df0234aa-893d-4371-8fe7-f2609f30c567"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grip Right"",
                    ""type"": ""Button"",
                    ""id"": ""a9bf1997-f0d9-4e35-a930-be438d5d85a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JoystickLeft"",
                    ""type"": ""Value"",
                    ""id"": ""56e5e8b5-cbd9-45d9-8c42-2351ebecb3f2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JoystickRight"",
                    ""type"": ""Value"",
                    ""id"": ""4b650980-58f7-49fe-b660-861f71170257"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThumbPressLeft"",
                    ""type"": ""Button"",
                    ""id"": ""3b57dbfe-1449-4aca-b0d4-d2545bdb59de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom Out Y Button"",
                    ""type"": ""Button"",
                    ""id"": ""4f60a28d-f37e-4b73-b551-70abe04307be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a7036b34-0434-44fb-ac71-543b648d1684"",
                    ""path"": ""<OculusTouchController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37572f0d-0a07-404a-af40-6d17e0e88e0a"",
                    ""path"": ""<OculusTouchController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad227f01-07a9-4552-9d17-8e4e3e0dfed2"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JoystickLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""312b958d-a68c-49e1-98d4-288c3be8982b"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JoystickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccb4d886-4d00-489e-a20b-2b4a9628cf4a"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbPressLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d9612e6-22a4-4e2a-bcc5-068ea7286641"",
                    ""path"": ""<OculusTouchController>/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom Out Y Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_GripLeft = m_Default.FindAction("Grip Left", throwIfNotFound: true);
        m_Default_GripRight = m_Default.FindAction("Grip Right", throwIfNotFound: true);
        m_Default_JoystickLeft = m_Default.FindAction("JoystickLeft", throwIfNotFound: true);
        m_Default_JoystickRight = m_Default.FindAction("JoystickRight", throwIfNotFound: true);
        m_Default_ThumbPressLeft = m_Default.FindAction("ThumbPressLeft", throwIfNotFound: true);
        m_Default_ZoomOutYButton = m_Default.FindAction("Zoom Out Y Button", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_GripLeft;
    private readonly InputAction m_Default_GripRight;
    private readonly InputAction m_Default_JoystickLeft;
    private readonly InputAction m_Default_JoystickRight;
    private readonly InputAction m_Default_ThumbPressLeft;
    private readonly InputAction m_Default_ZoomOutYButton;
    public struct DefaultActions
    {
        private @RagnarokVRInputActions m_Wrapper;
        public DefaultActions(@RagnarokVRInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @GripLeft => m_Wrapper.m_Default_GripLeft;
        public InputAction @GripRight => m_Wrapper.m_Default_GripRight;
        public InputAction @JoystickLeft => m_Wrapper.m_Default_JoystickLeft;
        public InputAction @JoystickRight => m_Wrapper.m_Default_JoystickRight;
        public InputAction @ThumbPressLeft => m_Wrapper.m_Default_ThumbPressLeft;
        public InputAction @ZoomOutYButton => m_Wrapper.m_Default_ZoomOutYButton;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @GripLeft.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGripLeft;
                @GripLeft.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGripLeft;
                @GripLeft.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGripLeft;
                @GripRight.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGripRight;
                @GripRight.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGripRight;
                @GripRight.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGripRight;
                @JoystickLeft.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJoystickLeft;
                @JoystickLeft.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJoystickLeft;
                @JoystickLeft.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJoystickLeft;
                @JoystickRight.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJoystickRight;
                @JoystickRight.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJoystickRight;
                @JoystickRight.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnJoystickRight;
                @ThumbPressLeft.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnThumbPressLeft;
                @ThumbPressLeft.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnThumbPressLeft;
                @ThumbPressLeft.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnThumbPressLeft;
                @ZoomOutYButton.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnZoomOutYButton;
                @ZoomOutYButton.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnZoomOutYButton;
                @ZoomOutYButton.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnZoomOutYButton;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GripLeft.started += instance.OnGripLeft;
                @GripLeft.performed += instance.OnGripLeft;
                @GripLeft.canceled += instance.OnGripLeft;
                @GripRight.started += instance.OnGripRight;
                @GripRight.performed += instance.OnGripRight;
                @GripRight.canceled += instance.OnGripRight;
                @JoystickLeft.started += instance.OnJoystickLeft;
                @JoystickLeft.performed += instance.OnJoystickLeft;
                @JoystickLeft.canceled += instance.OnJoystickLeft;
                @JoystickRight.started += instance.OnJoystickRight;
                @JoystickRight.performed += instance.OnJoystickRight;
                @JoystickRight.canceled += instance.OnJoystickRight;
                @ThumbPressLeft.started += instance.OnThumbPressLeft;
                @ThumbPressLeft.performed += instance.OnThumbPressLeft;
                @ThumbPressLeft.canceled += instance.OnThumbPressLeft;
                @ZoomOutYButton.started += instance.OnZoomOutYButton;
                @ZoomOutYButton.performed += instance.OnZoomOutYButton;
                @ZoomOutYButton.canceled += instance.OnZoomOutYButton;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnGripLeft(InputAction.CallbackContext context);
        void OnGripRight(InputAction.CallbackContext context);
        void OnJoystickLeft(InputAction.CallbackContext context);
        void OnJoystickRight(InputAction.CallbackContext context);
        void OnThumbPressLeft(InputAction.CallbackContext context);
        void OnZoomOutYButton(InputAction.CallbackContext context);
    }
}
